# Generated by Django 6.0.4 on 2026-04-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidate_viewing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosoungvien',
            name='chung_chi',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hosoungvien',
            name='du_an',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hosoungvien',
            name='gioi_thieu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hosoungvien',
            name='hoc_van',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hosoungvien',
            name='ngoai_ngu',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
