# Generated by Django 6.0.4 on 2026-04-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0002_add_job_detail_fields"),
        ("profiles", "0002_candidate_viewing_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidatePersonalityProfile",
            fields=[
                (
                    "ung_vien",
                    models.OneToOneField(
                        db_column="ung_vien_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="personality_profile",
                        serialize=False,
                        to="profiles.hosoungvien",
                    ),
                ),
                (
                    "traits_profile",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Hồ sơ đặc điểm tính cách của ứng viên",
                    ),
                ),
                (
                    "niche",
                    models.CharField(
                        blank=True,
                        help_text="Chuyên ngành chính",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CANDIDATE_PERSONALITY_PROFILE",
            },
        ),
        migrations.CreateModel(
            name="JobPersonalityRequirement",
            fields=[
                (
                    "tin",
                    models.OneToOneField(
                        db_column="tin_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="personality_requirement",
                        serialize=False,
                        to="jobs.tintuyendung",
                    ),
                ),
                (
                    "traits_required",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách đặc điểm tính cách yêu cầu dưới dạng JSON",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "JOB_PERSONALITY_REQUIREMENT",
            },
        ),
    ]
